### ISSUE TITLE
Incorrect times displayed on schedule

### ISSUE THREAD

**Issue by lovelaced** [venueless/venueless#61]
It seems as if the scheduled times don't display correctly in some circumstances. They display the correct times on tooltips on mouseover, but the timetable on the sidebar isn't correct. These do display correctly in pretalx; see screenshots below.
![2020-06-26-152452_989x639_scrot](https://user-images.githubusercontent.com/8581604/85862785-83bd9680-b7c2-11ea-9cf0-95cad1d8f5f5.png)
![2020-06-26-152510_701x822_scrot](https://user-images.githubusercontent.com/8581604/85862793-87511d80-b7c2-11ea-92da-876a9c5b9f54.png)

(Also maybe could be best to jump to today's date in the schedule UI by default if possible?).

**Comment by rashfael** [comment]
Pretalx integration is currently a bit experimental, since we did not have anyone using pretalx as of yet.
It's currently stuck in "demo mode" to show off the "jump to today's date" you mentioned https://github.com/venueless/venueless/blame/master/webapp/src/lib/timetravelMoment.js#L7 .
The timeline looks like it is the result of https://github.com/venueless/venueless/blame/master/webapp/src/components/pretalx/ScheduleDay.vue#L49

**Comment by raphaelm** [comment]
Since the schedule has been rewritten by now, I assume this is fixed?
