### ISSUE TITLE
Schedule Signaling

### ISSUE THREAD

**Issue by rashfael** [venueless/venueless#62]
One upcoming feature is better schedule integration and knowing which sessions/talks/workshops are "live".
Relying purely on the timestamp of the schedule is likely not enough since:
- Organizers may want to open workshops a few minutes in advance
- A talk might run into overtime and displaying the new talk title would be wrong™
- "Stream offline" currently relies on network status of the stream and also triggers on real network problems (or firewall etc) (relying on http status codes also seems a bit flimsy)

To address these issues, an organizer should be able to send updates on the current session/talk, which are then broadcast to all clients. A client should also receive the current talks on join.

The protocol could take several forms:
(we can assume that all clients always have an up-to-date schedule)

#### Relative commands 
`{room: X, action: 'next|previous|pause|...'}`
Pros:
- Clients can be very dumb

Cons: 
- Backend actually has to know what the schedule looks like
- Not able to arbitrarily change the talk
- Usual problems with aggregations in concurrent systems (Two organizers can say `next` at the same time, causing the backend to execute `next` twice)

#### Absolute commands
`{room: X, session: $ID | null}`

Pros:
- client has more freedom
- more robust over network

Cons:
- Possible client time drifts?

**Comment by rixx** [comment]
Both versions don't allow spontaneous changes to the title and related information, which I suspect will become an issue sooner rather than later, so we might just plan to add an optional `title` attribute directly?

I'd imagine the current schedule information would just be part of the room data, to be distributed initially with world information. I assume that just using `world.update` would be too generic and annoying, so I'd just give you `room.schedule`?
